export const GET_SOURCES = 'GET_SOURCES';
export const ADD_SOURCE = 'ADD_SOURCE';
export const DELETE_SOURCE = 'DELETE_SOURCE';
export const EDIT_SOURCE = 'EDIT_SOURCE';

export const GET_CURRICULUMS = 'GET_CURRICULUM';
export const ADD_CURRICULUM = 'ADD_CURRICULUM';
export const DELETE_CURRICULUM = 'DELETE_CURRICULUM';
export const EDIT_CURRICULUM = 'EDIT_CURRICULUM';